# Generated by Django 4.2.11 on 2024-09-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('CategoryId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('customerId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentId', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('permissionId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='pictures')),
                ('User', models.CharField(max_length=50)),
                ('Contact', models.TextField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_o_s.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('userId', models.CharField(max_length=10)),
                ('role', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_o_s.product')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_o_s.customer')),
                ('paymentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_o_s.payment')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_o_s.user')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('roleId', models.CharField(max_length=10)),
                ('permissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_o_s.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_o_s.customer')),
            ],
        ),
    ]
